[pytest]
minversion = 6.0
addopts = -ra -q
testpaths =
    test
asyncio_mode = auto
pythonpath = .
filterwarnings =
    ignore::pydantic.warnings.PydanticDeprecatedSince20
    ignore::DeprecationWarning:pydantic